### ISSUE TITLE
I think v2 is ready to go. Would you be willing to release it?

### ISSUE THREAD

**Issue by Chekote** [instaclick/php-webdriver#109]
Howdy!

I have been forced to switch to Selenium4 because I am now on an ARM Mac and that is the only Dockerized version that supports ARM. When doing so, I found that v1 of this package does not support it.

I was very pleased to find that you had done a bunch of hard work on getting it working with Selenium4 on the master branch. I see that you have V2 RC4, but that is missing a few fixes that are present in the master branch.

Are you ready to release v2? The last change to master was made back in July 2021, and I can confirm that b3af59147b7636377d3bad2118da8f0f4d1fae2a is working great on a pretty large project of ours when using Selenium4.

If you aren't ready to release v2 fully, could you release RC5 instead?

Thanks for all your hard work!

**Comment by robocoder** [comment]
Thanks for reminder. I tagged RC5.
