### ISSUE TITLE
W3C detection

### ISSUE THREAD

**Issue by robocoder** [instaclick/php-webdriver#115]
The runtime detection hasn't been validated across a broad spectrum of drivers:
* https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/Session.php#L128

Should we have a `strict` flag?
* if `strict` flag is false (default), obsolete methods are silently skipped (or emulated?)
* if `strict` flag is true, then obsolete/unknown methods will throw an exception, per AbstractWebDriver.php's getRequestMethod()

**Comment by mvorisek** [comment]
I think we can fire some request (`execute` request?) to detect W3C support on Session creation.

**Comment by robocoder** [comment]
Closing in favor of branch re-org in #124.
