### ISSUE TITLE
The "\WebDriver\Session::frame" isn't serializing arguments

### ISSUE THREAD

**Issue by aik099** [instaclick/php-webdriver#131]
According to the https://www.selenium.dev/documentation/legacy/json_wire_protocol/#sessionsessionidframe it is possible to specify a JSON reference to a WebElement for frame identification.

When attempting to do so using this code I'm getting an exception from the `\WebDriver\AbstractWebDriver::assertSerializable` method:

```php
$webElement = $webDriver->element('id', 'my_frame_id');
$webDriver->frame(array('id' => $webElement));
```

This is happening because the `\WebDriver\Element` class object isn't converted to a JSON interpretation. The only methods, that do serialization are `\WebDriver\Session::execute` and `\WebDriver\Session::execute_async`.

P.S.
I've checked other places in the code and this is the only one, where proper serialization is missing.

**Comment by aik099** [comment]
PR for 1.x branch added:
* https://github.com/instaclick/php-webdriver/pull/132

As for the `master` I have no idea how to implement it without a code duplication.

**Comment by aik099** [comment]
@robocoder , any ideas on how to fix this in the `master` branch?

**Comment by robocoder** [comment]
This should be fixed in `master` now.
