### ISSUE TITLE
Support for injecting CURL options into WebDriver

### ISSUE THREAD

**Issue by aik099** [instaclick/php-webdriver#51]
Right now WebDriver is using Curl to send commands to Selenium server. This works just fine, when we're able to make a connection.

However when server isn't responding for 1 minute then connection just drops (default socket connection timeout in PHP). E.g. https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/WebDriver.php#L72-L77

I propose that we allow user setting extra curl options (will go directly to `service.curl` used and to `curl_setopt` calls).

Related to Behat/MinkSelenium2Driver#48

**Comment by gggeek** [comment]
@robocoder could you post a gist to show how it is possible to inject anything?

I might be tired, but I have reversed the whole call chain backwards (using behat+mink), and I failed to find at any point where a service or class could be swapped out for another:

mink::getSession()->getDriver()
Selenium2Driver : calls new WebDriver() 
callas Servicefactory

**Comment by aik099** [comment]
That's the problem. There is no such point currently. The service container is creating curl class internally without way to inject anything: https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/AbstractWebDriver.php#L123

The factory is obtained via static method call.

**Comment by markpol** [comment]
Customizing the curl options for the webdriver service class is actually pretty straight forward.  Here is an example:

https://gist.github.com/markpol/d92918d21612f56a6548

**Comment by aik099** [comment]
It's possible yes, but surely isn't straightforward. To change 1 curl option you need to:

1. create sub-class of used curl service
2. hardcode new option in that sub-class constructor
3. replace the class in used service locator

If driver would be using dependency injection, then supplying CurlService right in it's constructor would be much easier.

**Comment by aik099** [comment]
I've created #73 with proposition to use dependency injection instead of service factory.
