### ISSUE TITLE
Exception when accessing SauceLabs

### ISSUE THREAD

**Issue by aik099** [instaclick/php-webdriver#59]
I'm using `SauceRest` class that comes with this library to communicate with SauceLabs service.

Recently my build failed (see https://travis-ci.org/aik099/phpunit-mink/jobs/44319424) with following exception:
```
PHP Fatal error:  Uncaught exception 'WebDriver\Exception\CurlExec' with message 'Curl error thrown for http PUT to https://saucelabs.com/rest/v1/aik099/jobs/471ebd9080014f919bea959e2ee1a928 with params: {"passed":true}
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none' in /home/travis/build/aik099/phpunit-mink/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
Stack trace:
#0 /home/travis/build/aik099/phpunit-mink/vendor/instaclick/php-webdriver/lib/WebDriver/Service/CurlService.php(97): WebDriver\Exception::factory(-1, 'Curl error thro...')
#1 /home/travis/build/aik099/phpunit-mink/vendor/instaclick/php-webdriver/lib/WebDriver/SauceLabs/SauceRest.php(76): WebDriver\Service\CurlService->execute('PUT', 'https://saucela...', Array, Array)
#2 /home/travis/build/aik099/phpunit-mink/vendor/instaclick/php-webdriver/lib/WebDriver/SauceLabs/SauceRest.php(208): WebDriver\SauceLabs\SauceRest->execute('PUT', 'aik099/jobs/471...', Array)
#3 /home/travis/build/aik099/phpunit-min in /home/travis/build/aik099/phpunit-mink/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php on line 155
```

As you can see from the stack trace the SSL certificate on SauceLabs appears to be broken or something like that.

To solve that problem I propose to add extra curl options in https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/SauceLabs/SauceRest.php#L76 that would allow to skip SSL certificate validation:

```
// don't verify SSL certificates
CURLOPT_SSL_VERIFYPEER => false,
CURLOPT_SSL_VERIFYHOST => false,
CURLOPT_HTTPHEADER => Array ('Expect:'),
```

**Comment by rmusslick** [comment]
Hi, is there any chance that you release this in a tag soon?

**Comment by aik099** [comment]
@rmusslick , haven't SauceLabs fixed it on their side already?

**Comment by rmusslick** [comment]
@aik099 
Well, i'm using "aik099/phpunit-mink": "~2.0" via composer, which uses instaclick/php-webdriver 1.4.1
and i'm getting an error using the setup for saucelabs.
"Fatal error: Uncaught exception 'WebDriver\Exception\CurlExec' with message 'Curl error thrown for http PUT to https://saucelabs.com/rest/v1/renemusslick/jobs/ with params: {"passed":true}
SSL certificate problem: unable to get local issuer certificate' "

If i add your 3 lines of code to SauceRest.php the test runs fine.
Just tested browserstack, with the a similar problem:

"Fatal error: Uncaught exception 'WebDriver\Exception\CurlExec' with message 'Curl error thrown for http PUT to https://www.browserstack.com/automate/sessions/.json
SSL certificate problem: self signed certificate in certificate chain' "

No idea how to fix this as well.

**Comment by aik099** [comment]
I see. I wonder how the `aik099/phpunit-mink` tests are passing without this fix. What if you try to use `~2.0@dev` version of PHPUnit-Mink? Will it work then?

**Comment by rmusslick** [comment]
Suprise, with "aik099/phpunit-mink": "~2.0@dev" (Removing aik099/phpunit-mink (v2.0.1)) and remaining instaclick/php-webdriver 1.4.1, the saucelabs and browserstack setup both work perfect. So it seems the problems i faced are resolved in your master but are not in a tag yet.

btw. thx for responding so fast :)

**Comment by aik099** [comment]
Then, as `aik099/phpunit-mink` library author I also was tired of waiting for `php-webdriver` release and created some kind of workaround inside `aik099/phpunit-mink`. I'll made a release now, so that you don't need to use dev version.

**Comment by aik099** [comment]
@rmusslick , I've created a release: https://github.com/minkphp/phpunit-mink/releases/tag/v2.1.0 . Wait couple of minutes before Packagist caches will refresh and then you can remove `@dev` part from Composer and after `composer update` the `2.1.0` version of `aik099/phpunit-mink` should be picked up.

**Comment by rmusslick** [comment]
@aik099 Thanks a lot.
