### ISSUE TITLE
Are there any plans to support remote file uploads?

### ISSUE THREAD

**Issue by chirimoya** [instaclick/php-webdriver#63]
I'm currently running Behat-Tests on Travis-CI and Saucelabs. But the remote file upload doesn't work. Attached some links with more information regarding this problem:
http://sauceio.com/index.php/2014/01/remote-file-uploads-with-selenium-php/
https://code.google.com/p/php-webdriver-bindings/wiki/HowToUploadFile

**Comment by robocoder** [comment]
Is this different from #36?

**Comment by chirimoya** [comment]
Not sure, but if I ran the tests locally on Selenium everything works fine. If I ran the tests on Saucelabs via remote tunnel I get following error:

`The requested URL returned error: 500 Internal Server Error (WebDriver\Exception\CurlExec)`

https://github.com/sulu-io/sulu/pull/1094/files#diff-9894497b5c4e94a173f223338b612933R176

**Comment by stof** [comment]
@chirimoya if you use Mink, you need to use the dev version of MinkSelenium2Driver to have that feature. The usage of the feature in Mink is not released yet.

**Comment by robocoder** [comment]
@chirimoya For SauceLabs, you have to also use `$session->file($arg);` to upload the file contents.

Example: https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L1191
