### ISSUE TITLE
How to work with popup windows?

### ISSUE THREAD

**Issue by moon0326** [instaclick/php-webdriver#68]
I'm trying to test Facebook sign-in, which involves popup windows. Is this even possible?

Looking at the session class, there aren't methods for selecting popup windows.

Thanks,
Moon

**Comment by aik099** [comment]
You're using this library directly or via Mink's Selenium2 Driver? I'm asking because Mink has method, that invoke this library, to switch between opened popup windows.

**Comment by moon0326** [comment]
@aik099 I'm actually using https://github.com/laracasts/integrated, but I have access to session object and others. If Mink has it, probably I will look into that if I don't get information soon.

**Comment by aik099** [comment]
Use following methods (these are this library Session methods, not Mink ones):

* `focusWindow` to switch to a window with a given name (see https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L407)
* `window_handles` to get all opened window names (see https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L472)

**Comment by moon0326** [comment]
@aik099  Thank you so much! focusWindow and window_handles are exactly what I needed :)
