### ISSUE TITLE
how to install with composer

### ISSUE THREAD

**Issue by emiglobetrotting** [instaclick/php-webdriver#69]
I downloaded the zip and extract the contents into a folder then install composer.phar and run 

    php composer.phar require instaclick/php-webdriver

but this couldn't install the dependencies. 

How can I install instaclick/php-webdriver with composer?

**Comment by robocoder** [comment]
It looks like satooshi/coveralls has some breaking changes. Try changing the constraint in composer.json to "~1.0" (instead of dev-master)

**Comment by robocoder** [comment]
Failing that, you can run composer with --no-dev.

**Comment by aik099** [comment]
Still the dependency on `satooshi/coveralls` needs to be changed because it blocks from installing WebDriver on PHP 5.4 and smaller.

**Comment by emiglobetrotting** [comment]
Constraint changed to "~1.0"  then instead of the previous command i ran

    php composer.phar install

The installation went through, thanks.

**Comment by robocoder** [comment]
Thanks. This is now fixed in composer.json
