### ISSUE TITLE
Allow subclassing of WebDriver class

### ISSUE THREAD

**Issue by gggeek** [instaclick/php-webdriver#71]
Currently the WebDriver class is declared final.

This is a pity, as the Selenium2Driver has a method `setWebDriver` which is typehinted against it.
This means that it is not easy for me to subclass either.
I propose that
- either we remove the 'final' keyword from WebDriver
- or we introduce an interface `WebDriverInterface` (all it needs is the `session` method) which can be used by 3rd parties for typehinting...

**Comment by gggeek** [comment]
ps: see https://github.com/minkphp/MinkSelenium2Driver/issues/231

**Comment by aik099** [comment]
In your particular case what is missing is ability to specify extra curl options for every curl call to WebDriver using JSONWireProtocol.

This topic was already discussed before (and you commented in there), but no viable solution was implemented. The @robocoder said, that ability to change curl options is an edge case and I should be injecting my own curl service to make it work. That's too much of an overhead really, just to set a proxy (what you needed) and curl timeout (what I needed).

See #53, #51

**Comment by robocoder** [comment]
FYI I also removed the `final` keyword from the WebDriver class.
