### ISSUE TITLE
Exception raised on closing connection with Web driver (Selenium)

### ISSUE THREAD

**Issue by vincenzodibiaggio** [instaclick/php-webdriver#75]
If a testsuite use the Selenium2Driver, session is not properly closed and after some time an exception will be raised:

`[WebDriver\Exception\UnknownError]                                            
  Session [ffcc81c9-cef1-4517-ab30-cb97b6114a47] was terminated due to TIMEOUT`
```
#0 /var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(141): WebDriver\Exception::factory(13, 'Session [08a112...')
#1 /var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/Session.php(157): WebDriver\AbstractWebDriver->curl('DELETE', '')
#2 /var/www/html/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(348): WebDriver\Session->close()
#3 /var/www/html/vendor/behat/mink/src/Session.php(78): Behat\Mink\Driver\Selenium2Driver->stop()
#4 /var/www/html/vendor/behat/mink/src/Mink.php(186): Behat\Mink\Session->stop()
#5 /var/www/html/vendor/behat/mink/src/Mink.php(46): Behat\Mink\Mink->stopSessions()
#6 [internal function]: Behat\Mink\Mink->__destruct()
#7 {main}
```

chrome / hub logs:

```
chrome_1           | 11:05:37.783 INFO - Executing: [find element: By.xpath: //html])
chrome_1           | 11:05:37.843 INFO - Done: [find element: By.xpath: //html]
chrome_1           | 11:05:37.856 INFO - Executing: [get text: 5 [[ChromeDriver: chrome on LINUX (96b0e9603a8e164374fec11e9525e1bb)] -> xpath: //html]])
chrome_1           | 11:05:38.275 INFO - Done: [get text: 5 [[ChromeDriver: chrome on LINUX (96b0e9603a8e164374fec11e9525e1bb)] -> xpath: //html]]
chrome_1           | 11:05:38.290 INFO - Executing: [take screenshot])
chrome_1           | 11:05:38.457 INFO - Done: [take screenshot]
chrome_1           | 11:05:38.555 INFO - Executing: [delete all cookies])
chrome_1           | 11:05:38.589 INFO - Done: [delete all cookies]
hub_1              | 11:06:08.981 WARN - session ext. key 08a1122c-5413-445d-a4bb-3b0f7fa0bf58 has TIMED OUT due to client inactivity and will be released.
chrome_1           | 11:06:08.984 INFO - Executing: [delete session: 08a1122c-5413-445d-a4bb-3b0f7fa0bf58])
chrome_1           | 11:06:09.177 INFO - Done: [delete session: 08a1122c-5413-445d-a4bb-3b0f7fa0bf58]
```

IMHO, the webdriver close a session that do not exist and an exception will be raised here:

`vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php`

```
// if not success, throw exception
        if ((int) $result['status'] !== 0) {
            throw WebDriverException::factory($result['status'], $message);
        }
```

because thre $result['status'] is 13.

If we call directly the proper function to close/delete sessions like

```if ($driver instanceof Selenium2Driver) {
        $driver->getWebDriverSession()->close();
        $driver->stop();
    }
```

an exception will be raised because of the result code that is 12 in this case.

**Comment by aik099** [comment]
This is still an error when attempting to stop session that is already stopped.

Now you at least know that session was timeout which in turn can indicate long running tests that start the session and forgot about it.

Not sure that it's a good idea to ignore timeout exception.

**Comment by vincenzodibiaggio** [comment]
@aik099 I don't want ignore this timeout but manage it. 

In my case I have tests both 'javascript' and not kind of tests and timeout occour after that javascript tests runs, when api test is running. When a new Feature is called, the exception is raised.

But, also if I avoid that closing the session programmatically, the status code in the response of Selenium is '12' and, because it's not '0', another exception will be raised.

I guess that if the status code in the response if one of standard Selenium codes, we need to manage it.

**Comment by aik099** [comment]
I see. Something like auto-restart session, when stopping failed due timeout error.

If that is the case, then this is best to managed in actual code using WebDriver, not web driver itself. E.g. in Mink or MinkExtension.

**Comment by vincenzodibiaggio** [comment]
Uhm, I gues that an autorestart session is not the solution because in my case, I don't need anymore a valid session because I don't have other test to run that use the WebDriver. 
IMHO I need only that the respose is managed in the proper way.

**Comment by aik099** [comment]
Then just ignoring timeout exception upon session stopping might be right solution for you. Since it's driver specific code, then https://github.com/minkphp/MinkSelenium2Driver/ is where change in code should be made (if maintainers agree).

**Comment by OskarStark** [comment]
any news here @vincenzodibiaggio

**Comment by robocoder** [comment]
Is this still applicable given recent changes to error handling in AbstractWebDriver.php to better accommodate the W3C drivers (e.g., chromedriver and geckodriver)?

**Comment by robocoder** [comment]
There's nothing to fix.

https://github.com/minkphp/MinkSelenium2Driver/blame/master/src/Selenium2Driver.php#L351 already wraps the session close in a try...catch block.

So, this call is redundant:
```
$driver->getWebDriverSession()->close();
```
