### ISSUE TITLE
New WebDriver specification breaks element retrieval

### ISSUE THREAD

**Issue by NicoHaase** [instaclick/php-webdriver#80]
According to https://w3c.github.io/webdriver/webdriver-spec.html#elements, which is in use in Selenium >= 3.5, the element name is no longer returned through `ELEMENT`, but through `element-6066-11e4-a52e-4f735466cecf`. This needs to be fixed in https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/Container.php#L206

Same behaviour is reported on:
- https://github.com/nightwatchjs/nightwatch/issues/1332
- https://github.com/SeleniumHQ/selenium/issues/4773

**Comment by robocoder** [comment]
See related issue #81

**Comment by NicoHaase** [comment]
Thanks @robocoder! Is there any chance to release v2.0.0 as a stable soon such that https://github.com/minkphp/MinkSelenium2Driver/issues/254 could be resolved?

**Comment by robocoder** [comment]
I've tagged 2.0.0-BETA so dev work can begin for `minkphp/MinkSelenium2Driver` assuming they stick with `instaclick/php-webdriver` in the short-term. However, I don't expect to tag a stable release until the W3C candidate recommendation is finalized and more widely implemented by other drivers.
