### ISSUE TITLE
Support for Selenium 3 W3C API

### ISSUE THREAD

**Issue by stof** [instaclick/php-webdriver#84]
Hi,

What is the progress regarding support of the W3C API, which is needed to support Firefox with Selenium 3 ?

**Comment by robocoder** [comment]
The protocol API seems stable, so I don't think there's anything left to implement here. But this has always been a thin wrapper around the protocol, so most of the dev effort falls on minkphp/MinkSeleniumDriver.

The spec itself is still getting tweaks, and while none of the implementations are 100% yet, broad vendor support is coming, so we should start working on https://github.com/minkphp/MinkSelenium2Driver/issues/254

https://w3c.github.io/webdriver/results/html/all.html

**Comment by stof** [comment]
@robocoder what are the plans on this one ? The 2.0-RC2 release still misses a bunch of things (see the related issues)

**Comment by stof** [comment]
Note that we (the Mink team) decided to rewrite our driver on top of `facebook/webdriver` instead, which abstracts the differences between the JsonWire and W3C protocols for us.

Supporting the W3C protocol using your new version would require us to duplicate all the work done in `facebook/webdriver` for this abstraction, and would require a driver rewrite for that anyway. So we decided it was a better move.
Thus, the current state of your W3C protocol support is broken (see the 3 issues listed above on October 3) and so cannot be used yet.

**Comment by robocoder** [comment]
Thanks for the update @stof. Sorry this has been a blocker for so long. We've been really busy and haven't had the cycles to maintain this abstraction.

**Comment by stof** [comment]
The analysis I made in https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-426680197 might mean you would not need to maintain it again much in the future (you will need to analyze the remaining usage...)

**Comment by DanielTakev** [comment]
Hi guys! Can someone tell my which chromedriver version starts using W3C, not JSON Wire protocol?

**Comment by robocoder** [comment]
2.0.0-RC7 should be complete wrt to the latest W3C spec but requires much more testing.

In the meantime, I'm closing this issue since projects are moving to `php-webdriver/php-webdriver` which is being more actively developed and tested.
