### ISSUE TITLE
The "window_handles" method missing on PHP 5.x

### ISSUE THREAD

**Issue by aik099** [instaclick/php-webdriver#85]
I'm not sure why, but suddenly the "window_handles" method disappeared in cases, when this library is used on PHP 5.x (e.g. https://travis-ci.org/minkphp/MinkSelenium2Driver/jobs/394658845).

Maybe different versions of this library are getting picked by Composer for PHP 5.x (non-working) and PHP 7.x (working).

Please help.

**Comment by robocoder** [comment]
Looks like Selenium2Driver's $wdSession didn't get initialized by calling Selrnium2Driver's start() method.

Have you tried disabling xdebug and phpunit's isolation feature? IIRC those led to test anomalies.

**Comment by aik099** [comment]
I haven't changed tests at all. There were no PRs for a while, but then on a new PR same test suite started to fail for PHP 5.x.

Just wanted to confirm, that you haven't changed anything related to PHP 5.x.

Will try to debug directly on Travis CI later then.

**Comment by robocoder** [comment]
It looks like Travis builds have been failing consistently for the past 2 yrs:
* https://travis-ci.org/minkphp/MinkSelenium2Driver/builds
* https://travis-ci.org/minkphp/MinkSelenium2Driver/pull_requests

**Comment by aik099** [comment]
I guess it is so unfortunately. It's likely because we're using xvfb with latest chrome/firefox version provided by Travis CI and some time ago Firefox version was released, that dropped Selenium 2 support and we're not ready for Selenium 3 yet.

The build, that connects to SauceLabs for testing won't have that Fatal Error.

**Comment by stof** [comment]
@aik099 FYI, we made changes on Mink side to stop auto-starting sessions when getting them from the Mink registry. Maybe the SeleniumDriver tests were relying on the implicit start (and they were not visiting any page before doing other stuff).
