### ISSUE TITLE
New stable release for 1.x

### ISSUE THREAD

**Issue by acbramley** [instaclick/php-webdriver#97]
It'd be great to get https://github.com/instaclick/php-webdriver/commit/36cd92de31fa9a0795dedf2317696bcbeafbccc7 into a stable release on 1.x as these cURL issues have caused all our builds to start failing when POSTing through selenium/standalone-chrome using ChromeDriver.

**Comment by robocoder** [comment]
I don't have a 1.x maintenance branch, so I cherry-picked the 3c50e949fc2c34e01ab387347dda2a1d13ee0cee and 36cd92de31fa9a0795dedf2317696bcbeafbccc7 commits, and tagged 1.4.6.

**Comment by acbramley** [comment]
Thanks @robocoder but it doesn't seem like the new release has been pushed to packagist? The latest stable is still showing as 1.4.5

**Comment by robocoder** [comment]
I changed the repo's webhook. Please take another look.
